/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_babytree_platform_reactnative_update_patch_BsdiffPatch
#define _Included_com_babytree_platform_reactnative_update_patch_BsdiffPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_babytree_platform_reactnative_update_patch_BsdiffPatch
 * Method:    bsdiffPatch
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_babytree_platform_reactnative_update_patch_BsdiffPatch_bsdiffPatch
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
